name: CI-CD BootcampCLT

on:
  push:
    branches: [ "master" ]

jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Restore
        run: dotnet restore ./BootcampCLT.sln

      - name: Build
        run: dotnet build ./BootcampCLT.sln -c Release --no-restore

      - name: Test
        run: dotnet test ./BootcampCLT.sln -c Release --no-build

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        run: |
          docker build -t 19942709/bootcampclt-api:${{ steps.meta.outputs.tag }} .
          docker push 19942709/bootcampclt-api:${{ steps.meta.outputs.tag }}

  cd:
    needs: ci
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy with Helm to Minikube
        working-directory: k8s/helm
        shell: cmd
        run: |
          helm upgrade --install bootcamp-api . --set image.tag=${{ needs.ci.outputs.image_tag }}
          kubectl rollout status deployment/bootcamp-api --timeout=120s
